[engine]
# proces interval (in seconds) is to set how often we want to recheck transaction status
# minimum 1 second, sensible maximum around 60 seconds
process-interval = 15
# proces interval after send (in seconds) is to set how long to wait after sending transaction before checking for confirmation
# sensible minimum 20 seconds, sensible maximum around 60 seconds
process-interval-after-send = 30
# proces interval after error (in seconds) is to set how long to wait after encountering error before trying again
# minimum 1 second, sensible maximum around 60 seconds
process-interval-after-error = 25

# proces interval after missing gas or token (in seconds)
# it is starting with checking every process-interval-after-no-gas-or-token-start
# and then increasing by multiplying by process-interval-after-no-gas-or-token-increase
# up to process-interval-after-no-gas-or-token-max
process-interval-after-no-gas-or-token-start = 20
process-interval-after-no-gas-or-token-max = 40
process-interval-after-no-gas-or-token-increase = 1.5

# report alive interval (in seconds) is to set how often we want to report that we are alive
# minimum 1 second, maximum is capped by gather-interval
report-alive-interval = 10
# gather interval (in seconds) is to set how often payments are gathered
# minimum 1 second, no maximum limit
gather-interval = 60
# gather payments on payment driver start (otherwise wait for first gather-interval)
gather-at-start = true
automatic-recover = false
# set to true to not respect deadlines attached to payments
ignore-deadlines = false


[chain.mainnet]
chain-name = "Mainnet"
chain-id = 1
currency-symbol = "ETH"
priority-fee = 1.01
max-fee-per-gas = 40.0
transaction-timeout = 100
token = { address = "0x7DD9c5Cba05E151C895FDe1CF355C9A1D5DA6429", symbol = "GLM" }
lock-contract = { address = "0xE440b576088d0a18340CAe5B2cff43502f1Cf588" }
confirmation-blocks = 1
block-explorer-url = "https://etherscan.io"
external-source-check-interval = 300

[[chain.mainnet.rpc-endpoints]]
names = """
    virginia.rpc.blxrbdn.com,
    public.blastapi.io,
    rpc.ankr.com/eth,rpc.flashbots.net,
    cloudflare-eth.com,
    ethereum.publicnode.com,
    rpc.payload.de
    """
endpoints = """
    https://virginia.rpc.blxrbdn.com,
    https://eth-mainnet.public.blastapi.io,
    https://rpc.ankr.com/eth,
    https://rpc.flashbots.net,
    https://cloudflare-eth.com,
    https://ethereum.publicnode.com,
    https://rpc.payload.de
    """
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.mainnet.rpc-endpoints]]
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120
dns-source = "mainnet.rpc-node.dev.golem.network."


[chain.goerli]
chain-name = "Goerli"
chain-id = 5
currency-symbol = "tETH"
priority-fee = 0.000001
max-fee-per-gas = 10.0
transaction-timeout = 100
token = { address = "0x33af15c79d64b85ba14aaffaa4577949104b22e8", symbol = "tGLM" }
multi-contract = { address = "0x7777784f803a7bf1d7f115f849d29ce5706da64a", max-at-once = 10 }
faucet-client = { max-eth-allowed = 0.009, faucet-srv = "_goerli-faucet._tcp", faucet-host = "faucet.testnet.golem.network", faucet-lookup-domain = "dev.golem.network", faucet-srv-port = 4001 }
mint-contract = { address = "0xCCA41b09C1F50320bFB41BD6822BD0cdBDC7d85C", max-glm-allowed = 400 }
confirmation-blocks = 0
block-explorer-url = "https://goerli.etherscan.io"
external-source-check-interval = 300

[[chain.goerli.rpc-endpoints]]
names = """
eth-goerli.g.alchemy.com/v2/demo,
eth-goerli.public.blastapi.io,
eth-goerli.api.onfinality.io/public,
rpc.goerli.mudit.blog,
endpoints.omniatech.io/v1/eth/goerli/public,
rpc.goerli.eth.gateway.fm,
goerli.blockpi.network/v1/rpc/public,
goerli.infura.io/v3/9aa,
rpc.ankr.com/eth_goerli,
ethereum-goerli-rpc.allthatnode.com,
rpc.slock.it/goerli,
www.ethercluster.com/goerli,
rpc.ankr.com/eth_goerli,
"""
endpoints = """
https://eth-goerli.g.alchemy.com/v2/demo,
https://eth-goerli.public.blastapi.io,
https://eth-goerli.api.onfinality.io/public,
https://rpc.goerli.mudit.blog,
https://endpoints.omniatech.io/v1/eth/goerli/public,
https://rpc.goerli.eth.gateway.fm,
https://goerli.blockpi.network/v1/rpc/public,
https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161,
https://rpc.ankr.com/eth_goerli,
https://ethereum-goerli-rpc.allthatnode.com,
https://rpc.slock.it/goerli,
https://www.ethercluster.com/goerli,
https://rpc.ankr.com/eth_goerli,
"""
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 12000

[[chain.goerli.rpc-endpoints]]
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 12000
dns-source = "goerli.rpc-node.dev.golem.network."

[chain.base]
chain-name = "Base"
chain-id = 8453
currency-symbol = "ETH"
priority-fee = 0.000001
max-fee-per-gas = 20.0
transaction-timeout = 100
attestation-contract = { address = "0x4200000000000000000000000000000000000021" }
schema-registry-contract = { address = "0x4200000000000000000000000000000000000020" }
token = { address = "0x1200000000000000000000000000000000000021", symbol = "GLM" }
confirmation-blocks = 0
block-explorer-url = "https://base.etherscan.io"
external-source-check-interval = 300

[[chain.base.rpc-endpoints]]
names = """
    base.gateway.tenderly.co,
    base-mainnet.public.blastapi.io,
    base.blockpi.network/v1/rpc/public,
    base.meowrpc.com,
    base-pokt.nodies.app,
    base.llamarpc.com
"""
endpoints = """
    https://base.gateway.tenderly.co,
    https://base-mainnet.public.blastapi.io,
    https://base.blockpi.network/v1/rpc/public,
    https://base.meowrpc.com,
    https://base-pokt.nodies.app,
    https://base.llamarpc.com
"""
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[chain.sepolia]
chain-name = "Sepolia"
chain-id = 11155111
currency-symbol = "tETH"
priority-fee = 0.000001
max-fee-per-gas = 20.0
transaction-timeout = 100
token = { address = "0x167b15ada84c63427c6c813B915a42eFC72E7175", symbol = "tGLM" }
mint-contract = { address = "0x31A2a20956a40c2F358Fa5cec59D55a9C5d6fF9A", max-glm-allowed = 400 }
lock-contract = { address = "0x35cA714deFa9482521659Cf9ee41F087f005335b" }
attestation-contract = { address = "0xC2679fBD37d54388Ce493F1DB75320D236e1815e" }
schema-registry-contract = { address = "0x0a7E2Ff54e76B8E6659aedc9103FB21c038050D0" }
confirmation-blocks = 0
block-explorer-url = "https://sepolia.etherscan.io"
external-source-check-interval = 300

[[chain.sepolia.rpc-endpoints]]
names = """
    endpoints.omniatech.io/v1/eth/sepolia/public
    ethereum-sepolia.blockpi.network/v1/rpc/public
    eth-sepolia.public.blastapi.io
    eth-sepolia-public.unifra.io
    sepolia.gateway.tenderly.co
    gateway.tenderly.co/public/sepolia
"""

endpoints = """
    https://endpoints.omniatech.io/v1/eth/sepolia/public
    https://ethereum-sepolia.blockpi.network/v1/rpc/public
    https://eth-sepolia.public.blastapi.io
    https://eth-sepolia-public.unifra.io
    https://sepolia.gateway.tenderly.co
    https://gateway.tenderly.co/public/sepolia
"""
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[chain.holesky]
chain-name = "Holesky"
chain-id = 17000
currency-symbol = "tETH"
priority-fee = 0.000001
max-fee-per-gas = 20.0
transaction-timeout = 100
wrapper-contract = { address = "0xE168bCa171ccf51066E2106d8955BF22705a6905" }
token = { address = "0x8888888815bf4DB87e57B609A50f938311EEd068", symbol = "tGLM" }
multi-contract = { address = "0xAaAAAaA00E1841A63342db7188abA84BDeE236c7", max-at-once = 10 }
mint-contract = { address = "0xFACe100969FF47EB58d2CF603321B581A84bcEaC", max-glm-allowed = 400 }
lock-contract = { address = "0x63704675f72A47a7a183112700Cb48d4B0A94332" }
distributor-contract = { address = "0xb7Fb99e86f93dc3047A12932052236d853065173" }
faucet-client = { max-eth-allowed = 0.009, faucet-srv = "_holesky-faucet._tcp", faucet-host = "faucet.testnet.golem.network", faucet-lookup-domain = "dev.golem.network", faucet-srv-port = 4002 }
confirmation-blocks = 0
block-explorer-url = "https://holesky.etherscan.io"
external-source-check-interval = 300

[[chain.holesky.rpc-endpoints]]
names = """
    holesky.publicnode.com,
    1rpc.io/holesky,
    rpc.ankr.com/eth_holesky,
    eth-holesky.public.blastapi.io,
    holesky.drpc.org,
    holesky.rpc.thirdweb.com
"""
endpoints = """
    https://holesky.publicnode.com,
    https://1rpc.io/holesky,
    https://rpc.ankr.com/eth_holesky,
    https://eth-holesky.public.blastapi.io,
    https://holesky.drpc.org,
    https://holesky.rpc.thirdweb.com
"""
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.holesky.rpc-endpoints]]
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120
dns-source = "holesky.rpc-node.dev.golem.network."

[chain.mumbai]
chain-name = "Mumbai testnet"
chain-id = 80001
currency-symbol = "tMATIC"
priority-fee = 1.0
max-fee-per-gas = 14.0
transaction-timeout = 60
token = { address = "0x2036807B0B3aaf5b1858EE822D0e111fDdac7018", symbol = "tGLM" }
multi-contract = { address = "0x800010D7d0d315DCA795110ecCf0127cBd76b89f", max-at-once = 10 }
confirmation-blocks = 1
block-explorer-url = "https://mumbai.polygonscan.com"
external-source-check-interval = 300

[[chain.mumbai.rpc-endpoints]]
names = """
polygon-mumbai.g.alchemy.com/v2/demo,
polygon-testnet.public.blastapi.io,
endpoints.omniatech.io/v1/matic/mumbai/public,
rpc-mumbai.maticvigil.com,
polygontestapi.terminet.io/rpc,
matic-mumbai.chainstacklabs.com,
matic-testnet-archive-rpc.bwarelabs.com,
rpc.ankr.com/polygon_mumbai,
polygon-testnet-archive.allthatnode.com:8545,
polygon-testnet-rpc.allthatnode.com:8545,
"""
endpoints = """
https://polygon-mumbai.g.alchemy.com/v2/demo,
https://polygon-testnet.public.blastapi.io,
https://endpoints.omniatech.io/v1/matic/mumbai/public,
https://rpc-mumbai.maticvigil.com,
https://polygontestapi.terminet.io/rpc,
https://matic-mumbai.chainstacklabs.com,
https://matic-testnet-archive-rpc.bwarelabs.com,
https://rpc.ankr.com/polygon_mumbai,
https://polygon-testnet-archive.allthatnode.com:8545,
https://polygon-testnet-rpc.allthatnode.com:8545,
"""
priority = 0
max-timeout-ms = 5000
allowed-head-behind-secs = 60

[[chain.mumbai.rpc-endpoints]]
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120
dns-source = "mumbai.rpc-node.dev.golem.network."

[chain.polygon]
chain-name = "Polygon mainnet"
chain-id = 137
currency-symbol = "MATIC"
priority-fee = 30.111
max-fee-per-gas = 500.0
transaction-timeout = 100
token = { address = "0x0B220b82F3eA3B7F6d9A1D8ab58930C064A2b5Bf", symbol = "GLM" }
wrapper-contract = { address = "0xbB6aad747990BB6F7f56851556A3277e474C656a" }
lock-contract = { address = "0x57ff7451E008647cbDB84e652B00ef05856Dba23" }
multi-contract = { address = "0x50100d4faf5f3b09987dea36dc2eddd57a3e561b", max-at-once = 10 }
attestation-contract = { address = "0x5E634ef5355f45A855d02D66eCD687b1502AF790" }
schema-registry-contract = { address = "0x7876EEF51A891E737AF8ba5A5E0f0Fd29073D5a7" }
confirmation-blocks = 1
block-explorer-url = "https://polygonscan.com"
external-source-check-interval = 300

[[chain.polygon.rpc-endpoints]]
names = """
polygon-rpc.com,
rpc-mainnet.maticvigil.com,
rpc-mainnet.matic.quiknode.pro,
bor.golem.network,
polygon-mainnet-archive.allthatnode.com:8545,
polygon-mainnet-rpc.allthatnode.com:8545,
"""
endpoints = """
https://polygon-rpc.com,
https://rpc-mainnet.maticvigil.com,
https://rpc-mainnet.matic.quiknode.pro,
https://bor.golem.network,
https://polygon-mainnet-archive.allthatnode.com:8545,
https://polygon-mainnet-rpc.allthatnode.com:8545,
"""
priority = 0
max-timeout-ms = 5000
allowed-head-behind-secs = 120

[[chain.polygon.rpc-endpoints]]
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120
dns-source = "polygon.rpc-node.dev.golem.network."


[chain.hoodi]
chain-name = "Hoodi"
chain-id = 560048
currency-symbol = "tETH"
priority-fee = 0.000001
max-fee-per-gas = 20.0
transaction-timeout = 100
wrapper-contract = { address = "0x7E69E00E00293D80F0f3E7e0Db5eab6D5d4E0EfF" }
token = { address = "0x55555555555556AcFf9C332Ed151758858bd7a26", symbol = "tGLM" }
multi-contract = { address = "0x222222222220C9269Cfb43eD434888F604d1dC21", max-at-once = 10 }
mint-contract = { address = "0x500F965199C63865A3E666cA3fF55B64F1c8Bc8b", max-glm-allowed = 400 }
lock-contract = { address = "0x472ef33B51f65FB2aDa50ffeB0e4A72e9ac22f52" }
distributor-contract = { address = "0x16684CcBC9b5c250D927d32f8F937fbbd058837A" }
faucet-client = { max-eth-allowed = 0.009, faucet-srv = "_hoodi-faucet._tcp", faucet-host = "faucet.testnet.golem.network", faucet-lookup-domain = "dev.golem.network", faucet-srv-port = 4004 }
confirmation-blocks = 0
block-explorer-url = "https://hoodi.etherscan.io"
external-source-check-interval = 300

[[chain.hoodi.rpc-endpoints]]
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 300
allowed-head-behind-secs = 120
dns-source = "hoodi.rpc-node.dev.golem.network."

[[chain.hoodi.rpc-endpoints]]
names = """
    hoodi.rpc-node.dev.golem.network
"""

endpoints = """
    https://hoodi.rpc-node.dev.golem.network/
"""
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120



